services:
  database:
    image: pgvector/pgvector:pg16
    container_name: pgvector_container
    environment:
      POSTGRES_USER: asd
      POSTGRES_PASSWORD: asd
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "asd" ]
      interval: 5s
      retries: 5
      timeout: 3s

  backend:
    build:
      context: .
      dockerfile: geonorge-server/Dockerfile
    volumes:
      - .:/app
    working_dir: /app/geonorge-server
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "
        echo 'üöÄ Starter create_vector.py' &&
        python /app/scripts/create_vector.py > /app/scripts/create_vector.log 2>&1 || echo '‚ùå create_vector.py feilet!' &&
        echo 'üöÄ Starter insert_csv.py' &&
        python /app/scripts/insert_csv.py > /app/scripts/insert_csv.log 2>&1 || echo '‚ùå insert_csv.py feilet!' &&
        echo 'üöÄ Starter server.py' &&
        python src/server.py > /app/scripts/server.log 2>&1 || echo '‚ùå server.py feilet!';
        tail -f /dev/null
      "
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./geonorge-app
      dockerfile: Dockerfile
    container_name: geogpt_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"